# need super user level permissions
language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t marshacb/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true marshacb/docker-react npm run test

# tell travis how to take our app and deploy it to aws
deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-east-1-584557161800"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
